apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - host: ingress.sanborn.me
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80