apiVersion: v1
kind: "Service"
metadata:
  name: grafana
  labels:
    name: grafana
  namespace: monitor
spec:
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30300
  selector:
    app: grafana
  type: NodePort