apiVersion: v1
kind: "Service"
metadata:
  name: prometheus
  labels:
    name: prometheus
  namespace: monitor
spec:
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 9090
  selector:
    app: prometheus
  type: NodePort