FROM jenkins/jenkins:lts

USER root
RUN apt-get update \
      && apt-get install --assume-yes  -y sudo \
      && apt install openjdk-8-jdk -y \
      && rm -rf /var/lib/apt/lists/*
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

RUN curl -O http://mirrors.hust.edu.cn/apache/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz \
      && tar -xvf apache-maven-3.6.0-bin.tar.gz -C /root/ \
      && export PATH=/root/apache-maven-3.6.0/bin:$PATH \
      && rm apache-maven-3.6.0-bin.tar.gz
USER jenkins
COPY plugins /usr/share/jenkins/plugins
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins
